@startuml
!theme reddress-darkblue
skinparam linetype ortho
skinparam classFontColor dimgrey
skinparam sequenceMessageAlign direction
skinparam groupInheritance 2
skinparam Roundcorner 20
skinparam shadowing true
skinparam class {
BackgroundColor #002D55FF
ArrowColor black
BorderColor #ADEFD1FF
AttributeFontName Candara
AttributeFontStyle Italic
FontColor  #DFDCE5FF
BorderThickness 0.25
}

' some class definitions
class InoversityLibraryManagementSystem {
    UserName: string
    UserPassword: string
    Login(): void
    Register(): void
    Logout(): void
}

' these classes will be grouped together
together {
class Staff {
    StaffNumber: string
    Department: string
    JobTitle: string
}

class Student {
    StudentNumber: string
    Faculty: string
    School: string
    Programme: string
    Courses: string
}

class User {
    Id: string
    FirstName: string
    LastName: string
    RoleLevel: string
    Password: string
    Verify()
    CheckAccount()
    GetDocuments()
}
}

together {
class Account {
    LoanedDocuments: List<string>
    ReservedDocuments: List<string>
    ReturnedDocuments: List<string>
    LostDocuments: List<string>
    FineAmount: integer
    CalculateFine()
}

class LibraryDatabase {
    Add()
    Delete()
    Update()
    Display()
    Search()
}

class Document {
    DocumentTitle: string
    Author: string
    Publication: string
    Reservation_status()
    DocRequest()
    DocFeedback()
    ReviewInfo()
    ShowDueDate()
}
}

' entity relationships
InoversityLibraryManagementSystem "1" *.. "*" User

LibraryDatabase "1" *. "*" Document

User "1" ..o "1" Account

LibraryDatabase "1" *.left. "*" Account

Document "*" .up.* "*" Account

User -left-> Student

User -right-> Staff
@enduml

