@startuml
!theme reddress-darkblue
skinparam linetype ortho
skinparam classFontColor dimgrey
skinparam sequenceMessageAlign direction
skinparam groupInheritance 2
skinparam Roundcorner 20
skinparam shadowing true
skinparam class {
BackgroundColor #002D55FF
ArrowColor black
BorderColor #ADEFD1FF
AttributeFontName Candara
AttributeFontStyle Italic
FontColor  #DFDCE5FF
BorderThickness 0.25
}

' some class definitions
class InoversityLibraryManagementSystem {
    userName: string
    userPassword: string
    login(): void
    register(): void
    logout(): void
}

' these classes will be grouped together
together {
class Staff {
    staffNumber: string
    department: string
    jobTitle: string
}

class Student {
    studentNumber: string
    faculty: string
    school: string
    programme: string
    courses: string
}

class User {
    firstName: string
    lastName: string
    id: string
    roleLevel: string
    password: string
    verify()
    checkAccount()
    getDocuments()
}
}

together {
class Account {
    loanedDocuments: List<string>
    reservedDocuments: List<string>
    returnedDocuments: List<string>
    lostDocuments: List<string>
    fineAmount: integer
    calculateFine()
}

class LibraryDatabase {
    add()
    delete()
    update()
    display()
    search()
}

class Document {
    doc_title: string
    author: string
    publication: string
    reservation_status()
    docRequest()
    docFeedback()
    reviewInfo()
    showDueDate()
}
}

' entity relationships
InoversityLibraryManagementSystem "1" *.. "*" User

LibraryDatabase "1" *. "*" Document

User "1" ..o "1" Account

LibraryDatabase "1" *.left. "*" Account

Document "*" .up.* "*" Account

User -left-> Student

User -right-> Staff
@enduml

